# Generated by Django 4.2 on 2025-01-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], max_length=50, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='time_first_mailing',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата первой рассылки'),
        ),
    ]
