# Generated by Django 4.2 on 2025-01-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_sending_periodicity_alter_sending_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
