# Generated by Django 4.2 on 2025-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_rename_status_sending_sending_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sending",
            name="time_first_mailing",
            field=models.DateTimeField(verbose_name="Начало рассылки"),
        ),
    ]
